### ISSUE TITLE
Plugin fails on files with top-level module comments

### ISSUE THREAD

**Issue by thomashoneyman** [Mateiadrielrafael/esbuild-plugin-purescript#1]
Hi @Mateiadrielrafael!

I noticed that this plugin fails when a module contains top level documentation comments, like:

```purs
-- | This is a module
module MyModule where
```

Here's the relevant code:

https://github.com/Mateiadrielrafael/esbuild-plugin-purescript/blob/ee417918443cebb838276817c8265e37bbc16c30/index.js#L13-L37

I believe this will need to ignore any comments when attempting to parse out a module name, which includes lines beginning with `--` or a block that begins with `{-` and ends with `-}`.

**Comment by Mateiadrielrafael** [comment]
Thanks, will fix when I get home!

**Comment by Mateiadrielrafael** [comment]
Hey, i think there was an issue deploying to npm, imma fix the ci later today
