### ISSUE TITLE
Watch mode doesn't detect changes to Purescript files.

### ISSUE THREAD

**Issue by vuolen** [Mateiadrielrafael/esbuild-plugin-purescript#2]
I am running esbuild on watch mode, but it does not rebuild when I change a Purescript file. The esbuild plugin API should have a solution for this.

**Comment by Mateiadrielrafael** [comment]
Thanks for the issue, I'll look into it!

**Comment by Mateiadrielrafael** [comment]
Hey! This issue should be fixed by the latest release. If the watch mode still does not work, we can reopen the issue.

**Comment by Mateiadrielrafael** [comment]
I guess we can close this for now
